// SPDX-Spec: vb6/frmOrderEntry (signed)
// SPDX-Archetype: canonical-vb6-winforms
//
// .NET 10 / WinForms projection of VB6 frmOrderEntry. Form_Load and
// btnSubmit_Click become typed event handlers wired in the constructor.
// VB6's "On Error Goto DBErrHandler" pattern lowers to a typed try/catch
// against OleDbException with explicit error-code filtering. The DAO
// recordset use is replaced by an OrderRepository (EF Core 10); the
// late-bound Excel.Application call is replaced by InvoiceExporter
// (ClosedXML).
//
// The implementation BODY is intentionally TODO — the scaffold is a
// contract, not a translation. The signed spec is the source of truth;
// the implementer fills the body and the 4-gate validation pipeline
// (compile / test pack / cross-runtime equivalence / property-based
// search) confirms parity against the original VB6.

using System.ComponentModel;
using System.Data.Common;
using System.Windows.Forms;

namespace Demo.OrderEntry;

/// <summary>
/// .NET 10 / WinForms projection of VB6 frmOrderEntry. Owns a single
/// scoped <see cref="OrderRepository"/> and an <see cref="InvoiceExporter"/>;
/// both are constructor-injected to support unit testing without spinning
/// up a real form.
/// </summary>
[SpecClaim("EH-1")]
public sealed class OrderEntryForm : Form
{
    private readonly OrderRepository _orders;
    private readonly InvoiceExporter _exporter;

    // Designer-allocated controls. Names match the original .frm property bag
    // so reviewers can map 1:1 against the source. WinForms designer code
    // lives in OrderEntryForm.Designer.cs (not generated by the scaffold —
    // the implementer adds it during code-completion).
    private TextBox txtCustomer = null!;
    private TextBox txtOrderId = null!;
    private Button btnSubmit = null!;
    private Label lblStatus = null!;

    public OrderEntryForm(OrderRepository orders, InvoiceExporter exporter)
    {
        _orders = orders ?? throw new ArgumentNullException(nameof(orders));
        _exporter = exporter ?? throw new ArgumentNullException(nameof(exporter));

        // Designer call lands here; controls are instantiated and laid out.
        // Once added, the scaffold's btnSubmit_Click wiring works as-is.
        InitializeComponent();

        // EH-1: btnSubmit.Click maps to the VB6 btnSubmit_Click handler.
        btnSubmit.Click += OnSubmitClick;
    }

    /// <summary>
    /// EH-1: Form_Load equivalent. WinForms OnLoad runs AFTER the form's
    /// handle is created but BEFORE the form is shown — same semantic as
    /// VB6 Form_Load. Populate dropdowns and pre-seed the next order id.
    /// </summary>
    /// <remarks>
    /// VB6 source used <c>dbsOrders.Execute</c> directly. The .NET 10
    /// port delegates to <see cref="OrderRepository"/> which holds the
    /// EF Core context.
    /// </remarks>
    [SpecClaim("EH-1")]
    [SpecClaim("INV-1")]
    protected override void OnLoad(EventArgs e)
    {
        base.OnLoad(e);
        // TODO: populate cmbProducts; seed txtOrderId from
        // _orders.NextOrderIdAsync(). The signed spec's Form_Load entry
        // (see example-form-load.json) drives this.
    }

    /// <summary>
    /// EH-1 + INV-1: btnSubmit_Click handler. Validates customer field,
    /// inserts the Orders row via the repository, then writes the invoice
    /// via the exporter. OE-1 (On Error Goto DBErrHandler) lowers to a
    /// typed try/catch filtering on the DAO 3022 / 3134 codes the SME
    /// signed off on.
    /// </summary>
    [SpecClaim("EH-1")]
    [SpecClaim("INV-1")]
    [SpecClaim("INV-2")]
    [SpecClaim("OE-1")]
    [SpecClaim("DP-1")]
    [SpecClaim("SE-1")]
    [SpecClaim("EC-1")]
    [SpecClaim("EC-2")]
    private async void OnSubmitClick(object? sender, EventArgs e)
    {
        // DP-1: VB6 implicit txtCustomer (in String context) → explicit .Text.
        var customer = txtCustomer.Text?.Trim() ?? "";

        // INV-1 + EC-1: empty customer short-circuits with no external state touched.
        if (customer.Length == 0)
        {
            lblStatus.Text = "Customer required";
            return;
        }

        var orderId = long.TryParse(txtOrderId.Text, out var parsed) ? parsed : 0;

        try
        {
            // INV-2 + SE-1: exactly-once insert; RecordsAffected = 1 asserted
            // before any downstream side effect.
            await _orders.InsertAsync(new Order(orderId, customer));
        }
        catch (DbException ex) when (IsKnownDaoError(ex))
        {
            // OE-1: DBErrHandler equivalent. Show the message; do NOT
            // attempt the Excel export. Other DbException codes rethrow
            // and propagate as unhandled — matches VB6 default dialog.
            lblStatus.Text = ex.Message;
            return;
        }

        // The Excel write happens only on the success path — same as VB6.
        await _exporter.ExportInvoiceAsync(orderId, ResolveTargetPath(orderId));
        lblStatus.Text = "Submitted";
    }

    // OE-1: the VB6 handler branches on Err.Number 3022 (duplicate PK) and
    // 3134 (SQL syntax). Surface the same code filter explicitly. Other
    // codes are NOT swallowed — they bubble out of the catch.
    private static bool IsKnownDaoError(DbException ex) =>
        ex.ErrorCode == 3022 || ex.ErrorCode == 3134;

    // Hard-coded template path in the VB6 source becomes a per-order path
    // here. Q-1 (open question in the spec) asks whether to keep this
    // hard-coded or move to config; until the SME decides, the scaffold
    // surfaces it as a private method.
    private static string ResolveTargetPath(long orderId) =>
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
            "Orders", $"Invoice-{orderId}.xlsx");

    // Designer placeholder. The implementer adds this method (or moves it
    // to OrderEntryForm.Designer.cs) to materialise the controls.
    [EditorBrowsable(EditorBrowsableState.Never)]
    private void InitializeComponent()
    {
        // TODO: instantiate txtCustomer, txtOrderId, btnSubmit, lblStatus
        // and add to Controls. Layout matches the original .frm property
        // bag — see the FormLayout output from parser_sidecar.vb6_parser.
        throw new NotImplementedException(
            "Implementer: add the WinForms designer code here. The signed " +
            "spec's enclosing_module = 'frmOrderEntry'; see the parser's " +
            "FormLayout output for the control list + property bag.");
    }
}

/// <summary>EF Core entity backing the Orders table.</summary>
public sealed record Order(long Id, string CustomerName);
