"""
fpc sidecar — REST surface for Delphi compile + run.

Endpoints
---------
GET  /health                       liveness probe
POST /compile                      body: { "sources": [{ "path", "content" }],
                                           "linkAs": "executable" | "library",
                                           "mainProgram": "Main.dpr" (optional) }
                                   -> { "artifactId", "exitCode", "log",
                                        "warningCount", "errorCount", "durationMs" }

POST /run                          body: { "artifactId", "stdin": "<json>" or "" }
                                   -> { "exitCode", "stdout", "stderr",
                                        "durationMs", "timedOut" }

POST /compile-and-run              body: { sources, stdin, timeoutMs?, mainProgram? }
                                   -> shorthand that returns combined result.

The contract MATCHES the gfortran-sidecar's contract verbatim except for
the optional `mainProgram` field. The API's CrossRuntimeValidator can
dispatch by source-language without learning a second protocol.

Compilation
-----------
The compiler is invoked as:
    fpc -Mdelphi -O- -gl -Sg -Sc -vewn -Fu<unit_dirs> -o<output> <main>
where:
    -Mdelphi          Delphi-7+ syntax mode (the only one most Indy code uses).
    -O-               No optimisation. Matches gfortran -O0 — we want the
                      reference binary to behave predictably, not be fast.
    -gl               Include line-number info in the binary.
    -Sg               Allow LABEL / GOTO (some Indy code still uses them).
    -Sc               Allow C-style operators (`+=`, `-=`, etc.).
    -vewn             Verbose level: errors + warnings + notes (no hints).
    -Fu<dir>          Add unit-search dir for every subdirectory of the build.
    -o<path>          Output binary path.

If `mainProgram` is not supplied we pick the first `.dpr` in sources.
If no `.dpr` exists and linkAs == "executable" we synthesise a minimal
driver `Main.dpr` that just `uses` the first unit — handy for the small
property-test snippets generated by the Hypothesis sidecar (Phase 9.0.g).

Artifacts live under /var/tmp/fpc-runs/<artifactId>/ for the lifetime
of the container. Same lifetime contract as the gfortran sidecar.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import time
import uuid
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from fpc_sidecar import __version__

logging.basicConfig(
    level=logging.INFO,
    format='{"ts":"%(asctime)s","level":"%(levelname)s","service":"astra-fpc","msg":"%(message)s"}',
)
log = logging.getLogger("astra.fpc")

WORKDIR = Path(os.environ.get("FPC_WORKDIR", "/var/tmp/fpc-runs"))
WORKDIR.mkdir(parents=True, exist_ok=True)

COMPILE_TIMEOUT_S = 120
DEFAULT_RUN_TIMEOUT_MS = 30_000

app = FastAPI(title="Astra fpc sidecar", version=__version__)


# ────────────────────────────────────────────────────────────────────────
# Pydantic models — same shape as gfortran-sidecar plus mainProgram.
# ────────────────────────────────────────────────────────────────────────


class PascalSource(BaseModel):
    path: str = Field(..., description="Path relative to the build dir (e.g. IdSMTPMin.pas / Main.dpr).")
    content: str


class CompileRequest(BaseModel):
    sources: list[PascalSource]
    link_as: str = Field("executable", alias="linkAs")
    extra_flags: list[str] = Field(default_factory=list, alias="extraFlags")
    main_program: Optional[str] = Field(None, alias="mainProgram")

    class Config:
        populate_by_name = True


class CompileResult(BaseModel):
    artifact_id: str = Field(..., alias="artifactId")
    exit_code: int = Field(..., alias="exitCode")
    log: str
    warning_count: int = Field(..., alias="warningCount")
    error_count: int = Field(..., alias="errorCount")
    duration_ms: int = Field(..., alias="durationMs")

    class Config:
        populate_by_name = True


class RunRequest(BaseModel):
    artifact_id: str = Field(..., alias="artifactId")
    stdin: str = ""
    timeout_ms: int = Field(DEFAULT_RUN_TIMEOUT_MS, alias="timeoutMs")

    class Config:
        populate_by_name = True


class RunResult(BaseModel):
    exit_code: int = Field(..., alias="exitCode")
    stdout: str
    stderr: str
    duration_ms: int = Field(..., alias="durationMs")
    timed_out: bool = Field(..., alias="timedOut")

    class Config:
        populate_by_name = True


class CompileAndRunRequest(BaseModel):
    sources: list[PascalSource]
    stdin: str = ""
    timeout_ms: int = Field(DEFAULT_RUN_TIMEOUT_MS, alias="timeoutMs")
    extra_flags: list[str] = Field(default_factory=list, alias="extraFlags")
    main_program: Optional[str] = Field(None, alias="mainProgram")

    class Config:
        populate_by_name = True


class CompileAndRunResult(BaseModel):
    compile: CompileResult
    run: Optional[RunResult] = None
    skipped_run_reason: Optional[str] = Field(None, alias="skippedRunReason")

    class Config:
        populate_by_name = True


# ────────────────────────────────────────────────────────────────────────
# Routes
# ────────────────────────────────────────────────────────────────────────


@app.get("/health")
def health():
    return {
        "service": "astra-fpc",
        "version": __version__,
        "workdir": str(WORKDIR),
        "fpcVersion": _fpc_version(),
    }


@app.post("/compile", response_model=CompileResult, response_model_by_alias=True)
def compile_endpoint(req: CompileRequest) -> CompileResult:
    return _compile(req.sources, req.link_as, req.extra_flags, req.main_program)


@app.post("/run", response_model=RunResult, response_model_by_alias=True)
def run_endpoint(req: RunRequest) -> RunResult:
    return _run(req.artifact_id, req.stdin, req.timeout_ms)


@app.post("/compile-and-run", response_model=CompileAndRunResult, response_model_by_alias=True)
def compile_and_run_endpoint(req: CompileAndRunRequest) -> CompileAndRunResult:
    compile_result = _compile(req.sources, "executable", req.extra_flags, req.main_program)
    if compile_result.exit_code != 0:
        return CompileAndRunResult(
            compile=compile_result,
            run=None,
            skipped_run_reason="compile_failed",
        )
    run_result = _run(compile_result.artifact_id, req.stdin, req.timeout_ms)
    return CompileAndRunResult(compile=compile_result, run=run_result)


# ────────────────────────────────────────────────────────────────────────
# Workers
# ────────────────────────────────────────────────────────────────────────


def _compile(
    sources: list[PascalSource],
    link_as: str,
    extra_flags: list[str],
    main_program: Optional[str],
) -> CompileResult:
    if not sources:
        raise HTTPException(status_code=400, detail="At least one source file is required.")

    artifact_id = uuid.uuid4().hex
    build_dir = WORKDIR / artifact_id
    build_dir.mkdir(parents=True, exist_ok=False)

    # Materialise sources to disk.
    abs_paths: list[Path] = []
    for src in sources:
        rel = src.path.lstrip("/").replace("\\", "/")
        abs_path = build_dir / rel
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        abs_path.write_text(src.content, encoding="utf-8")
        abs_paths.append(abs_path)

    # Pick the entry point.
    main_path = _pick_main_program(abs_paths, build_dir, main_program, link_as)

    # Unit search paths: every subdirectory of the build that contains a .pas/.pp.
    unit_dirs = sorted({p.parent for p in abs_paths if p.suffix.lower() in (".pas", ".pp")})
    fu_flags = [f"-Fu{d.relative_to(build_dir)}" for d in unit_dirs if d != build_dir]

    output = build_dir / ("app" if link_as == "executable" else "lib.a")
    flags = [
        "-Mdelphi",       # Delphi mode for VCL / Indy compatibility.
        "-O-",            # No optimisation; predictable reference binary.
        "-gl",            # Line-number debug info.
        "-Sg",            # Allow LABEL / GOTO.
        "-Sc",            # Allow C-style operators (+=, etc.).
        "-vewn",          # Errors + warnings + notes (no hints).
        *fu_flags,
        f"-o{output.name}",
    ] + list(extra_flags)
    cmd = ["fpc", *flags, str(main_path.relative_to(build_dir))]

    t0 = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(build_dir),
            capture_output=True,
            text=True,
            timeout=COMPILE_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        shutil.rmtree(build_dir, ignore_errors=True)
        raise HTTPException(status_code=504, detail=f"fpc exceeded {COMPILE_TIMEOUT_S}s") from None

    elapsed_ms = int((time.monotonic() - t0) * 1000)
    log_text = (
        f"=== fpc {' '.join(cmd[1:])} ===\n"
        f"{proc.stdout}\n"
        + (f"=== stderr ===\n{proc.stderr}\n" if proc.stderr else "")
        + f"=== exit {proc.returncode} ===\n"
    )
    # fpc tags its diagnostic lines with "Error:", "Warning:", "Note:" — same
    # pattern as gfortran, so the counters look identical to the API consumer.
    err_count = log_text.count("Error:") + log_text.count("Fatal:")
    warn_count = log_text.count("Warning:")
    log.info(
        "compile artifact=%s files=%d main=%s exit=%d ms=%d errors=%d warnings=%d",
        artifact_id, len(sources), main_path.name, proc.returncode, elapsed_ms, err_count, warn_count,
    )
    return CompileResult(
        artifact_id=artifact_id,
        exit_code=proc.returncode,
        log=log_text,
        warning_count=warn_count,
        error_count=err_count,
        duration_ms=elapsed_ms,
    )


def _run(artifact_id: str, stdin_text: str, timeout_ms: int) -> RunResult:
    build_dir = WORKDIR / artifact_id
    binary = build_dir / "app"
    if not binary.exists():
        raise HTTPException(status_code=404, detail=f"Artifact {artifact_id} has no executable.")

    t0 = time.monotonic()
    timed_out = False
    try:
        proc = subprocess.run(
            [str(binary)],
            cwd=str(build_dir),
            input=stdin_text,
            capture_output=True,
            text=True,
            timeout=max(1, timeout_ms) / 1000,
        )
        exit_code = proc.returncode
        stdout = proc.stdout
        stderr = proc.stderr
    except subprocess.TimeoutExpired as ex:
        timed_out = True
        exit_code = -1
        stdout = ex.stdout.decode("utf-8", errors="replace") if ex.stdout else ""
        stderr = (ex.stderr.decode("utf-8", errors="replace") if ex.stderr else "") + \
                 f"\n[fpc-sidecar] killed after {timeout_ms}ms"

    elapsed_ms = int((time.monotonic() - t0) * 1000)
    log.info(
        "run artifact=%s exit=%d ms=%d timed_out=%s stdout_bytes=%d stderr_bytes=%d",
        artifact_id, exit_code, elapsed_ms, timed_out, len(stdout), len(stderr),
    )
    return RunResult(
        exit_code=exit_code,
        stdout=stdout,
        stderr=stderr,
        duration_ms=elapsed_ms,
        timed_out=timed_out,
    )


# ────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────


def _pick_main_program(
    abs_paths: list[Path],
    build_dir: Path,
    requested: Optional[str],
    link_as: str,
) -> Path:
    if requested:
        candidate = (build_dir / requested).resolve()
        if not candidate.exists():
            raise HTTPException(
                status_code=400,
                detail=f"mainProgram '{requested}' not found in supplied sources.",
            )
        return candidate

    dprs = [p for p in abs_paths if p.suffix.lower() == ".dpr"]
    if dprs:
        return dprs[0]

    if link_as != "executable":
        # Library link — fpc compiles each unit independently. Pass the
        # first .pas as the entry point; fpc will -c it.
        return abs_paths[0]

    # No .dpr supplied, but caller asked for an executable. Synthesise a
    # one-liner driver so the Hypothesis sidecar can ship a single unit
    # and the sidecar wires it into a runnable program.
    first_pas = next((p for p in abs_paths if p.suffix.lower() == ".pas"), None)
    if not first_pas:
        raise HTTPException(
            status_code=400,
            detail="No .dpr or .pas source supplied; cannot link executable.",
        )
    unit_name = first_pas.stem
    driver = build_dir / "AstraDriver.dpr"
    driver.write_text(
        f"program AstraDriver;\nuses {unit_name};\nbegin\nend.\n",
        encoding="utf-8",
    )
    return driver


def _fpc_version() -> str:
    try:
        proc = subprocess.run(
            ["fpc", "-iV"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return proc.stdout.strip() or proc.stderr.strip() or "unknown"
    except Exception:
        return "unavailable"


def main() -> None:
    import uvicorn
    port = int(os.environ.get("FPC_PORT", "51055"))
    uvicorn.run(
        "fpc_sidecar.server:app",
        host="0.0.0.0",
        port=port,
        log_level="warning",
        access_log=False,
    )


if __name__ == "__main__":
    main()
