namespace Astra.Api.Persistence.Entities;

/// <summary>
/// Phase 8.0.b — A dependency-aware migration plan for one corpus.
///
/// Generated by <see cref="Llm.Dependency.MigrationPlanner"/> from the
/// Phase 8.0.a <see cref="Llm.Dependency.DependencyGraphBuilder"/>'s
/// output. A plan groups every routine in a corpus's latest source
/// version into ordered <see cref="MigrationWave"/>s. Approved plans
/// drive what engineers see on the "what should I migrate next" page;
/// they're recomputable any time the underlying source changes.
///
/// Lifecycle:
///   draft → approved → archived
/// At most one approved plan per (corpusId, sourceVersionId) tuple at
/// a time — approving a new plan automatically archives any prior
/// approved plan for the same tuple.
/// </summary>
public sealed class MigrationPlan
{
    public Guid Id { get; set; }
    public Guid CorpusId { get; set; }
    public Guid SourceVersionId { get; set; }

    /// <summary>"draft" | "approved" | "archived".</summary>
    public string Status { get; set; } = "draft";

    /// <summary>The strategy used to generate this plan
    /// (e.g. "topological-leaves-first"). Phase 8.0.b ships one
    /// strategy; 8.0.e adds more.</summary>
    public string StrategyName { get; set; } = "topological-leaves-first";

    /// <summary>JSON blob of strategy-specific options (e.g. a CSV of
    /// business-priority routine names for the business-priority
    /// strategy). Empty <c>"{}"</c> for the default strategy.</summary>
    public string StrategyOptionsJson { get; set; } = "{}";

    public int TotalRoutines { get; set; }
    public int TotalWaves { get; set; }

    /// <summary>One-line human summary, e.g. "12 waves, 47 routines,
    /// 2 cycles."</summary>
    public string Summary { get; set; } = "";

    public string? GeneratedBy { get; set; }
    public string? ApprovedBy { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset? ApprovedAt { get; set; }
    public DateTimeOffset? ArchivedAt { get; set; }
}

/// <summary>
/// One wave in a migration plan. Wave membership is denormalised onto
/// this row as a JSON array of subroutine IDs so re-planning doesn't
/// touch every subroutine row — important because the plan can be
/// recomputed any time the call graph changes.
/// </summary>
public sealed class MigrationWave
{
    public Guid Id { get; set; }
    public Guid MigrationPlanId { get; set; }

    /// <summary>1-based wave number. Wave 1 is the first set of
    /// routines that can be migrated (typically leaves with no
    /// in-corpus callees).</summary>
    public int WaveNumber { get; set; }

    public string Name { get; set; } = "";

    /// <summary>JSON array of subroutine IDs assigned to this wave.</summary>
    public string PlannedRoutineIdsJson { get; set; } = "[]";

    /// <summary>"planned" | "in_progress" | "completed".</summary>
    public string Status { get; set; } = "planned";

    public DateTimeOffset? TargetStartDate { get; set; }
    public DateTimeOffset? TargetEndDate { get; set; }
    public DateTimeOffset? ActualCompletedAt { get; set; }

    /// <summary>Cached count of routines in this wave — denormalised
    /// for the wave-list view so we don't parse the JSON every render.
    /// Live counts (signed/scaffolded/validated/committed) are
    /// computed on read; they drift too fast to denormalise.</summary>
    public int RoutineCount { get; set; }
}
