"""
g++ sidecar — REST surface for C++ compile + run.

Endpoints
---------
GET  /health                       liveness probe
POST /compile                      body: { "sources": [{ "path", "content" }],
                                           "linkAs": "executable" | "library",
                                           "mainProgram": "main.cpp" (optional),
                                           "extraFlags": [...] }
                                   -> { "artifactId", "exitCode", "log",
                                        "warningCount", "errorCount", "durationMs" }

POST /run                          body: { "artifactId", "stdin": "<json>" or "" }
                                   -> { "exitCode", "stdout", "stderr",
                                        "durationMs", "timedOut" }

POST /compile-and-run              body: { sources, stdin, timeoutMs?, mainProgram? }
                                   -> shorthand that returns combined result.

The contract MATCHES the fpc / gfortran / gnucobol sidecars verbatim so the
API's CrossRuntimeValidator only has to add a dispatch arm.

Compilation
-----------
The compiler is invoked as:
    g++ -std=c++20 -O0 -g -Wall -Wno-unused -fno-strict-aliasing -I<inc_dirs>
        -o <output> <source files>

`-fno-strict-aliasing` is deliberate — it keeps `reinterpret_cast`-heavy code
runnable for equivalence testing without forcing the user to fix every UB
case before the harness can compare outputs. The cpp.schema.json's
undefined_behaviors claim is the place to surface those concerns; the
sidecar's job is to RUN the reference binary, not to be a UB linter.

If `mainProgram` is not supplied we pick the first source whose path ends in
`.cpp` / `.cc` / `.cxx`. If only headers (`.h` / `.hpp`) are supplied and
linkAs == "executable" we synthesise a minimal `Main.cpp` that just
`#include`s the first header — useful for the small property-test snippets
generated by the Hypothesis sidecar.

Artifacts live under /var/tmp/gpp-runs/<artifactId>/ for the lifetime of
the container.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import time
import uuid
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from gpp_sidecar import __version__

logging.basicConfig(
    level=logging.INFO,
    format='{"ts":"%(asctime)s","level":"%(levelname)s","service":"astra-gpp","msg":"%(message)s"}',
)
log = logging.getLogger("astra.gpp")

WORKDIR = Path(os.environ.get("GPP_WORKDIR", "/var/tmp/gpp-runs"))
WORKDIR.mkdir(parents=True, exist_ok=True)

COMPILE_TIMEOUT_S = 120
DEFAULT_RUN_TIMEOUT_MS = 30_000

app = FastAPI(title="Astra g++ sidecar", version=__version__)


# ────────────────────────────────────────────────────────────────────────
# Pydantic models — same shape as fpc-sidecar plus mainProgram.
# ────────────────────────────────────────────────────────────────────────


class CppSource(BaseModel):
    path: str = Field(..., description="Path relative to the build dir (e.g. main.cpp / fmt/core.h).")
    content: str


class CompileRequest(BaseModel):
    sources: list[CppSource]
    link_as: str = Field("executable", alias="linkAs")
    extra_flags: list[str] = Field(default_factory=list, alias="extraFlags")
    main_program: Optional[str] = Field(None, alias="mainProgram")

    class Config:
        populate_by_name = True


class CompileResult(BaseModel):
    artifact_id: str = Field(..., alias="artifactId")
    exit_code: int = Field(..., alias="exitCode")
    log: str
    warning_count: int = Field(..., alias="warningCount")
    error_count: int = Field(..., alias="errorCount")
    duration_ms: int = Field(..., alias="durationMs")

    class Config:
        populate_by_name = True


class RunRequest(BaseModel):
    artifact_id: str = Field(..., alias="artifactId")
    stdin: str = ""
    timeout_ms: int = Field(DEFAULT_RUN_TIMEOUT_MS, alias="timeoutMs")

    class Config:
        populate_by_name = True


class RunResult(BaseModel):
    exit_code: int = Field(..., alias="exitCode")
    stdout: str
    stderr: str
    duration_ms: int = Field(..., alias="durationMs")
    timed_out: bool = Field(..., alias="timedOut")

    class Config:
        populate_by_name = True


class CompileAndRunRequest(BaseModel):
    sources: list[CppSource]
    stdin: str = ""
    timeout_ms: int = Field(DEFAULT_RUN_TIMEOUT_MS, alias="timeoutMs")
    extra_flags: list[str] = Field(default_factory=list, alias="extraFlags")
    main_program: Optional[str] = Field(None, alias="mainProgram")

    class Config:
        populate_by_name = True


class CompileAndRunResult(BaseModel):
    compile: CompileResult
    run: Optional[RunResult] = None
    skipped_run_reason: Optional[str] = Field(None, alias="skippedRunReason")

    class Config:
        populate_by_name = True


# ────────────────────────────────────────────────────────────────────────
# Routes
# ────────────────────────────────────────────────────────────────────────


@app.get("/health")
def health():
    return {
        "service": "astra-gpp",
        "version": __version__,
        "workdir": str(WORKDIR),
        "gppVersion": _gpp_version(),
    }


@app.post("/compile", response_model=CompileResult, response_model_by_alias=True)
def compile_endpoint(req: CompileRequest) -> CompileResult:
    return _compile(req.sources, req.link_as, req.extra_flags, req.main_program)


@app.post("/run", response_model=RunResult, response_model_by_alias=True)
def run_endpoint(req: RunRequest) -> RunResult:
    return _run(req.artifact_id, req.stdin, req.timeout_ms)


@app.post("/compile-and-run", response_model=CompileAndRunResult, response_model_by_alias=True)
def compile_and_run_endpoint(req: CompileAndRunRequest) -> CompileAndRunResult:
    compile_result = _compile(req.sources, "executable", req.extra_flags, req.main_program)
    if compile_result.exit_code != 0:
        return CompileAndRunResult(
            compile=compile_result,
            run=None,
            skipped_run_reason="compile_failed",
        )
    run_result = _run(compile_result.artifact_id, req.stdin, req.timeout_ms)
    return CompileAndRunResult(compile=compile_result, run=run_result)


# ────────────────────────────────────────────────────────────────────────
# Workers
# ────────────────────────────────────────────────────────────────────────


_CPP_EXTS = (".cpp", ".cc", ".cxx", ".c++")
_HEADER_EXTS = (".h", ".hpp", ".hxx", ".h++", ".ipp")


def _compile(
    sources: list[CppSource],
    link_as: str,
    extra_flags: list[str],
    main_program: Optional[str],
) -> CompileResult:
    if not sources:
        raise HTTPException(status_code=400, detail="At least one source file is required.")

    artifact_id = uuid.uuid4().hex
    build_dir = WORKDIR / artifact_id
    build_dir.mkdir(parents=True, exist_ok=False)

    abs_paths: list[Path] = []
    for src in sources:
        rel = src.path.lstrip("/").replace("\\", "/")
        abs_path = build_dir / rel
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        abs_path.write_text(src.content, encoding="utf-8")
        abs_paths.append(abs_path)

    main_path = _pick_main_program(abs_paths, build_dir, main_program, link_as)
    cpp_paths = [p for p in abs_paths if p.suffix.lower() in _CPP_EXTS] or [main_path]

    # Include dirs: every directory that contains a header.
    inc_dirs = sorted({p.parent for p in abs_paths if p.suffix.lower() in _HEADER_EXTS})
    inc_flags = [f"-I{d.relative_to(build_dir)}" for d in inc_dirs if d != build_dir]
    if not inc_flags:
        inc_flags = ["-I."]

    output = build_dir / ("app" if link_as == "executable" else "lib.a")
    flags = [
        "-std=c++20",
        "-O0",
        "-g",
        "-Wall",
        "-Wno-unused",
        "-fno-strict-aliasing",
        *inc_flags,
        "-o", str(output.name),
    ] + list(extra_flags)
    if link_as != "executable":
        flags = [f for f in flags if f != "-o" and f != str(output.name)]
        flags += ["-c"]

    cmd = ["g++", *flags] + [str(p.relative_to(build_dir)) for p in cpp_paths]

    t0 = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(build_dir),
            capture_output=True,
            text=True,
            timeout=COMPILE_TIMEOUT_S,
        )
    except subprocess.TimeoutExpired:
        shutil.rmtree(build_dir, ignore_errors=True)
        raise HTTPException(status_code=504, detail=f"g++ exceeded {COMPILE_TIMEOUT_S}s") from None

    elapsed_ms = int((time.monotonic() - t0) * 1000)
    log_text = (
        f"=== g++ {' '.join(cmd[1:])} ===\n"
        f"{proc.stdout}\n"
        + (f"=== stderr ===\n{proc.stderr}\n" if proc.stderr else "")
        + f"=== exit {proc.returncode} ===\n"
    )
    err_count = log_text.count("error:")
    warn_count = log_text.count("warning:")
    log.info(
        "compile artifact=%s files=%d main=%s exit=%d ms=%d errors=%d warnings=%d",
        artifact_id, len(sources), main_path.name, proc.returncode, elapsed_ms, err_count, warn_count,
    )
    return CompileResult(
        artifact_id=artifact_id,
        exit_code=proc.returncode,
        log=log_text,
        warning_count=warn_count,
        error_count=err_count,
        duration_ms=elapsed_ms,
    )


def _run(artifact_id: str, stdin_text: str, timeout_ms: int) -> RunResult:
    build_dir = WORKDIR / artifact_id
    binary = build_dir / "app"
    if not binary.exists():
        raise HTTPException(status_code=404, detail=f"Artifact {artifact_id} has no executable.")

    t0 = time.monotonic()
    timed_out = False
    try:
        proc = subprocess.run(
            [str(binary)],
            cwd=str(build_dir),
            input=stdin_text,
            capture_output=True,
            text=True,
            timeout=max(1, timeout_ms) / 1000,
        )
        exit_code = proc.returncode
        stdout = proc.stdout
        stderr = proc.stderr
    except subprocess.TimeoutExpired as ex:
        timed_out = True
        exit_code = -1
        stdout = ex.stdout.decode("utf-8", errors="replace") if ex.stdout else ""
        stderr = (ex.stderr.decode("utf-8", errors="replace") if ex.stderr else "") + \
                 f"\n[gpp-sidecar] killed after {timeout_ms}ms"

    elapsed_ms = int((time.monotonic() - t0) * 1000)
    log.info(
        "run artifact=%s exit=%d ms=%d timed_out=%s stdout_bytes=%d stderr_bytes=%d",
        artifact_id, exit_code, elapsed_ms, timed_out, len(stdout), len(stderr),
    )
    return RunResult(
        exit_code=exit_code,
        stdout=stdout,
        stderr=stderr,
        duration_ms=elapsed_ms,
        timed_out=timed_out,
    )


# ────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────


def _pick_main_program(
    abs_paths: list[Path],
    build_dir: Path,
    requested: Optional[str],
    link_as: str,
) -> Path:
    if requested:
        candidate = (build_dir / requested).resolve()
        if not candidate.exists():
            raise HTTPException(
                status_code=400,
                detail=f"mainProgram '{requested}' not found in supplied sources.",
            )
        return candidate

    cpps = [p for p in abs_paths if p.suffix.lower() in _CPP_EXTS]
    if cpps:
        return cpps[0]

    if link_as != "executable":
        return abs_paths[0]

    # Header-only sources but caller asked for an executable — synthesise a
    # one-liner driver that includes the first header.
    first_header = next((p for p in abs_paths if p.suffix.lower() in _HEADER_EXTS), None)
    if not first_header:
        raise HTTPException(
            status_code=400,
            detail="No .cpp or .h source supplied; cannot link executable.",
        )
    driver = build_dir / "AstraDriver.cpp"
    rel_include = first_header.relative_to(build_dir).as_posix()
    driver.write_text(
        f"#include \"{rel_include}\"\nint main() {{ return 0; }}\n",
        encoding="utf-8",
    )
    return driver


def _gpp_version() -> str:
    try:
        proc = subprocess.run(
            ["g++", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        first = (proc.stdout or proc.stderr or "").splitlines()
        return first[0].strip() if first else "unknown"
    except Exception:
        return "unavailable"


def main() -> None:
    import uvicorn
    port = int(os.environ.get("GPP_PORT", "51057"))
    uvicorn.run(
        "gpp_sidecar.server:app",
        host="0.0.0.0",
        port=port,
        log_level="warning",
        access_log=False,
    )


if __name__ == "__main__":
    main()
