import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, CheckCircle2, ChevronDown, Layers, Play, Settings2 } from 'lucide-react';
import { clsx } from 'clsx';
import {
  api,
  ApiError,
  type MigrationPlanStrategy,
  type MigrationPlanWave,
  type MigrationPlanWaveRoutine,
} from '@/lib/api';
import { Badge } from '@/components/Badge';
import { Button } from '@/components/Button';
import { Card, CardBody } from '@/components/Card';
import { ErrorBlock } from '@/components/ErrorBlock';
import { PageHero } from '@/components/PageHero';
import { Skeleton } from '@/components/Skeleton';

/**
 * Phase 8.0.b — Migration plan for a corpus.
 *
 * Shows the wave-by-wave assignment generated by the
 * MigrationPlanner. Engineer + observer see the plan read-only;
 * admin can recompute (generate a fresh draft) or approve a draft.
 *
 * The plan is "stable" in the sense that the same call graph
 * produces the same wave assignment every time — recomputing only
 * matters when the source changes (re-ingest).
 */
export function MigrationPlanPage() {
  const params = useParams<{ id: string }>();
  const corpusId = params.id!;
  const navigate = useNavigate();
  const qc = useQueryClient();

  const whoami = useQuery({ queryKey: ['whoami'], queryFn: api.whoami });
  const isAdmin = whoami.data?.persona === 'admin';
  const corpus = useQuery({
    queryKey: ['corpus', corpusId],
    queryFn: () => api.getCorpus(corpusId),
  });

  const plan = useQuery({
    queryKey: ['migration-plan', corpusId],
    queryFn: () => api.getCurrentMigrationPlan(corpusId),
    retry: false,
  });

  const strategiesQuery = useQuery({
    queryKey: ['migration-plan-strategies'],
    queryFn: () => api.listMigrationPlanStrategies(),
  });
  const strategies = strategiesQuery.data?.data ?? [];
  const defaultStrategyName = useMemo(
    () => strategies.find((s) => s.isDefault)?.name ?? strategies[0]?.name ?? '',
    [strategies],
  );

  const [pickerOpen, setPickerOpen] = useState(false);
  const [selectedStrategy, setSelectedStrategy] = useState<string>('');
  const [optionsText, setOptionsText] = useState<string>('{}');
  const [optionsError, setOptionsError] = useState<string | null>(null);

  // Sync the picker default to the current plan's strategy (if any),
  // otherwise to the platform default. Done in an effect so refetches
  // don't fight user edits.
  useEffect(() => {
    if (selectedStrategy) return;
    const planStrategy = plan.data?.plan.strategyName;
    if (planStrategy) setSelectedStrategy(planStrategy);
    else if (defaultStrategyName) setSelectedStrategy(defaultStrategyName);
  }, [plan.data?.plan.strategyName, defaultStrategyName, selectedStrategy]);

  const selectedStrategyDef = strategies.find((s) => s.name === selectedStrategy);

  const generate = useMutation({
    mutationFn: () => {
      // Resolve options for the selected strategy. Strategies whose
      // options schema is an empty object (no fields required) get
      // sent {} even if the picker was never opened.
      const hasOptionFields = strategyHasFields(selectedStrategyDef);
      let options: Record<string, unknown> | undefined;
      if (hasOptionFields) {
        try {
          options = optionsText.trim() ? JSON.parse(optionsText) : {};
          setOptionsError(null);
        } catch (e) {
          setOptionsError(`Options JSON did not parse: ${(e as Error).message}`);
          throw e;
        }
      }
      return api.generateMigrationPlan(corpusId, {
        strategy: selectedStrategy || undefined,
        options,
      });
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ['migration-plan', corpusId] }),
  });
  const approve = useMutation({
    mutationFn: (planId: string) => api.approveMigrationPlan(planId),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['migration-plan', corpusId] }),
  });

  if (corpus.isPending) {
    return (
      <div className="mx-auto max-w-[1200px] space-y-3 p-6">
        <Skeleton className="h-8 w-72" />
        <Skeleton className="h-40" />
      </div>
    );
  }

  // 404 from the plan endpoint = no plan yet. Render an empty-state CTA.
  const noPlanYet = plan.isError && plan.error instanceof ApiError && plan.error.status === 404;

  return (
    <div className="mx-auto max-w-[1200px] space-y-6 p-6 lg:p-10 fadeup" data-testid="migration-plan-page">
      <PageHero
        tone="indigo"
        eyebrow={corpus.data?.name ?? corpusId}
        title="Migration plan"
        lead="Dependency-aware wave assignment for the corpus's latest source version. Wave 1 starts with leaf routines (no in-corpus callees); each subsequent wave depends only on routines in earlier waves."
      />

      {isAdmin && (
        <Card data-testid="strategy-picker-card">
          <CardBody className="space-y-3">
            <button
              type="button"
              onClick={() => setPickerOpen((o) => !o)}
              className="flex w-full items-center justify-between gap-2 text-left"
              data-testid="strategy-picker-toggle"
            >
              <span className="flex items-center gap-2 text-body text-ink-primary">
                <Settings2 className="h-4 w-4 text-ink-tertiary" />
                Strategy: <span className="font-mono">{selectedStrategy || '—'}</span>
                {selectedStrategyDef?.isDefault && (
                  <span className="font-mono text-caption text-ink-tertiary">[default]</span>
                )}
              </span>
              <ChevronDown
                className={clsx(
                  'h-4 w-4 text-ink-tertiary transition-transform',
                  pickerOpen && 'rotate-180',
                )}
              />
            </button>
            {pickerOpen && (
              <div className="space-y-3 border-t border-border-subtle pt-3">
                <div className="space-y-1">
                  <label className="text-caption font-medium uppercase tracking-wider text-ink-tertiary">
                    Strategy
                  </label>
                  <select
                    value={selectedStrategy}
                    onChange={(e) => {
                      setSelectedStrategy(e.target.value);
                      setOptionsText('{}');
                      setOptionsError(null);
                    }}
                    disabled={strategiesQuery.isPending}
                    className="w-full rounded border border-border-subtle bg-raised px-2 py-1 font-mono text-body-sm text-ink-primary"
                    data-testid="strategy-select"
                  >
                    {strategies.map((s) => (
                      <option key={s.name} value={s.name}>
                        {s.name}
                        {s.isDefault ? ' (default)' : ''}
                      </option>
                    ))}
                  </select>
                  {selectedStrategyDef && (
                    <p className="text-body-sm text-ink-secondary">
                      {selectedStrategyDef.description}
                    </p>
                  )}
                </div>
                {selectedStrategyDef && strategyHasFields(selectedStrategyDef) && (
                  <div className="space-y-1">
                    <label className="text-caption font-medium uppercase tracking-wider text-ink-tertiary">
                      Options (JSON)
                    </label>
                    <textarea
                      value={optionsText}
                      onChange={(e) => {
                        setOptionsText(e.target.value);
                        setOptionsError(null);
                      }}
                      rows={6}
                      placeholder={placeholderFor(selectedStrategyDef.name)}
                      className="w-full rounded border border-border-subtle bg-raised px-2 py-1 font-mono text-caption text-ink-primary"
                      data-testid="strategy-options-textarea"
                    />
                    <details className="text-caption text-ink-tertiary">
                      <summary className="cursor-pointer">Schema</summary>
                      <pre className="mt-1 overflow-auto rounded bg-sunken p-2 font-mono">
                        {JSON.stringify(selectedStrategyDef.optionsSchema, null, 2)}
                      </pre>
                    </details>
                    {optionsError && (
                      <p className="text-caption text-feedback-error">{optionsError}</p>
                    )}
                  </div>
                )}
                <p className="font-mono text-caption text-ink-tertiary">
                  These values are used the next time you click <em>Generate</em> or{' '}
                  <em>Recompute</em>.
                </p>
              </div>
            )}
          </CardBody>
        </Card>
      )}

      {plan.isPending && !noPlanYet && <Skeleton className="h-40" />}

      {noPlanYet && (
        <Card>
          <CardBody className="space-y-3 text-center">
            <Layers className="mx-auto h-8 w-8 text-ink-tertiary" />
            <p className="text-body text-ink-primary">No migration plan yet for this corpus.</p>
            <p className="text-body-sm text-ink-secondary">
              The planner reads the dependency graph and assigns every routine to a wave based
              on what it CALLs. Same graph in → same plan out, every time.
            </p>
            {isAdmin && (
              <Button
                variant="primary"
                onClick={() => generate.mutate()}
                disabled={generate.isPending}
                data-testid="generate-migration-plan"
              >
                <Play className={clsx('h-4 w-4', generate.isPending && 'animate-pulse')} />
                {generate.isPending ? 'Generating…' : 'Generate plan'}
              </Button>
            )}
            {!isAdmin && (
              <p className="font-mono text-caption text-ink-tertiary">
                Admin can generate the first plan. Switch persona from the top-right menu.
              </p>
            )}
          </CardBody>
        </Card>
      )}

      {plan.isError && !noPlanYet && (
        <ErrorBlock title="Could not load migration plan" message={String(plan.error)} />
      )}

      {plan.data && (
        <>
          <Card>
            <CardBody className="flex flex-wrap items-center justify-between gap-3">
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge tone={planTone(plan.data.plan.status)}>{plan.data.plan.status}</Badge>
                  <span className="font-mono text-caption text-ink-tertiary">
                    {plan.data.plan.strategyName}
                  </span>
                  <span className="font-mono text-caption text-ink-tertiary">
                    {plan.data.plan.totalWaves} waves · {plan.data.plan.totalRoutines} routines
                  </span>
                </div>
                <p className="text-body text-ink-primary">{plan.data.plan.summary}</p>
                <p className="font-mono text-caption text-ink-tertiary">
                  generated by {plan.data.plan.generatedBy ?? '—'} ·{' '}
                  {new Date(plan.data.plan.createdAt).toLocaleString()}
                  {plan.data.plan.approvedAt && (
                    <>
                      {' '}· approved by {plan.data.plan.approvedBy ?? '—'} ·{' '}
                      {new Date(plan.data.plan.approvedAt).toLocaleString()}
                    </>
                  )}
                </p>
              </div>
              {isAdmin && (
                <div className="flex flex-wrap items-center gap-2">
                  {plan.data.plan.status === 'draft' && (
                    <Button
                      variant="primary"
                      onClick={() => approve.mutate(plan.data!.plan.id)}
                      disabled={approve.isPending}
                      data-testid="approve-migration-plan"
                    >
                      <CheckCircle2 className="h-4 w-4" /> Approve plan
                    </Button>
                  )}
                  <Button
                    variant="secondary"
                    onClick={() => generate.mutate()}
                    disabled={generate.isPending}
                    data-testid="regenerate-migration-plan"
                  >
                    <Play className={clsx('h-4 w-4', generate.isPending && 'animate-pulse')} />
                    {generate.isPending ? 'Generating…' : 'Recompute plan'}
                  </Button>
                </div>
              )}
            </CardBody>
          </Card>

          {generate.isError && (
            <ErrorBlock
              title="Recompute failed"
              message={
                generate.error instanceof ApiError
                  ? generate.error.message
                  : String(generate.error)
              }
            />
          )}
          {approve.isError && (
            <ErrorBlock
              title="Approval failed"
              message={
                approve.error instanceof ApiError
                  ? approve.error.message
                  : String(approve.error)
              }
            />
          )}

          <div className="space-y-3">
            {plan.data.waves.map((w) => (
              <WaveCard
                key={w.id}
                wave={w}
                onOpenRoutine={(routineId) => navigate(`/subroutines/${routineId}`)}
              />
            ))}
          </div>
        </>
      )}

      <Card>
        <CardBody>
          <Link to={`/corpora/${corpusId}`} className="text-body-sm text-accent hover:underline">
            ← Back to corpus
          </Link>
          {' · '}
          <Link
            to={`/corpora/${corpusId}/dependency-graph`}
            className="text-body-sm text-accent hover:underline"
          >
            Open dependency graph
          </Link>
        </CardBody>
      </Card>
    </div>
  );
}

function planTone(status: string): 'success' | 'review' | 'superseded' | 'neutral' {
  if (status === 'approved') return 'success';
  if (status === 'draft') return 'review';
  if (status === 'archived') return 'superseded';
  return 'neutral';
}

/** True when the strategy declares any option fields beyond an empty {}. */
function strategyHasFields(s: MigrationPlanStrategy | undefined): boolean {
  if (!s) return false;
  const schema = s.optionsSchema as { properties?: Record<string, unknown> };
  return !!schema?.properties && Object.keys(schema.properties).length > 0;
}

/** Per-strategy hint text shown in the options textarea placeholder. */
function placeholderFor(strategyName: string): string {
  switch (strategyName) {
    case 'business-priority':
      return '{\n  "priorities": { "FIND_FIT": 1, "INV_READ": 2 },\n  "defaultPriority": 99\n}';
    case 'pilot-then-scale':
      return '{\n  "pilotRoutineNames": ["FIND_FIT", "HYBRD1"]\n}';
    default:
      return '{}';
  }
}

function WaveCard({
  wave,
  onOpenRoutine,
}: {
  wave: MigrationPlanWave;
  onOpenRoutine: (routineId: string) => void;
}) {
  const lc = wave.liveCounts;
  // Wave colour gradient — wave 1 (earliest, safest) → wave 5 (latest,
  // top-level orchestration). Caps at 5; corpora with deeper plans
  // cycle back to the final tone.
  const waveBucket = Math.min(5, Math.max(1, wave.waveNumber)) as 1 | 2 | 3 | 4 | 5;
  const stripe: Record<1 | 2 | 3 | 4 | 5, string> = {
    1: 'bg-wave-1',
    2: 'bg-wave-2',
    3: 'bg-wave-3',
    4: 'bg-wave-4',
    5: 'bg-wave-5',
  };
  const eyebrow: Record<1 | 2 | 3 | 4 | 5, string> = {
    1: 'text-emerald-ink',
    2: 'text-teal-ink',
    3: 'text-indigo-ink',
    4: 'text-violet-ink',
    5: 'text-amber-ink',
  };
  return (
    <Card data-testid={`migration-wave-${wave.waveNumber}`} className="relative overflow-hidden">
      <span
        aria-hidden
        className={clsx('absolute left-0 top-0 h-full w-1.5', stripe[waveBucket])}
      />
      <CardBody className="space-y-2 pl-5">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <p className={clsx('font-mono text-caption font-semibold uppercase tracking-wider', eyebrow[waveBucket])}>
              wave {wave.waveNumber}
            </p>
            <h3 className="text-body-lg font-semibold text-ink-primary">{wave.name}</h3>
          </div>
          <div className="text-right font-mono text-caption text-ink-tertiary">
            <div>{wave.routineCount} routines</div>
            <div>
              signed: {lc.signed} · scaffolded: {lc.scaffolded} · committed: {lc.committed}
            </div>
          </div>
        </div>
        <ul className="grid grid-cols-1 gap-1 md:grid-cols-2 lg:grid-cols-3">
          {wave.routines.map((r) => (
            <RoutinePill key={r.id} routine={r} onClick={() => onOpenRoutine(r.id)} />
          ))}
        </ul>
      </CardBody>
    </Card>
  );
}

function RoutinePill({
  routine,
  onClick,
}: {
  routine: MigrationPlanWaveRoutine;
  onClick: () => void;
}) {
  const tone =
    routine.state === 'COMMITTED' ? 'success' :
    routine.state === 'SCAFFOLDED' ? 'scaffolded' :
    routine.state === 'SIGNED' ? 'success' :
    routine.state === 'DRAFT' || routine.state === 'IN_REVIEW' ? 'review' :
    'neutral';
  return (
    <li>
      <button
        onClick={onClick}
        className="group flex w-full items-center justify-between gap-2 rounded border border-border-subtle bg-raised px-2 py-1 text-left hover:bg-sunken"
      >
        <span className="truncate font-mono text-body-sm text-ink-primary">{routine.name}</span>
        <span className="flex items-center gap-1">
          <Badge tone={tone}>{routine.state}</Badge>
          <ArrowRight className="h-3 w-3 text-ink-tertiary opacity-0 group-hover:opacity-100" />
        </span>
      </button>
    </li>
  );
}
