import { Link, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, CheckCircle2, Layers, Play } from 'lucide-react';
import { clsx } from 'clsx';
import {
  api,
  ApiError,
  type MigrationPlanWave,
  type MigrationPlanWaveRoutine,
} from '@/lib/api';
import { Badge } from '@/components/Badge';
import { Button } from '@/components/Button';
import { Card, CardBody } from '@/components/Card';
import { ErrorBlock } from '@/components/ErrorBlock';
import { Skeleton } from '@/components/Skeleton';

/**
 * Phase 8.0.b — Migration plan for a corpus.
 *
 * Shows the wave-by-wave assignment generated by the
 * MigrationPlanner. Engineer + observer see the plan read-only;
 * admin can recompute (generate a fresh draft) or approve a draft.
 *
 * The plan is "stable" in the sense that the same call graph
 * produces the same wave assignment every time — recomputing only
 * matters when the source changes (re-ingest).
 */
export function MigrationPlanPage() {
  const params = useParams<{ id: string }>();
  const corpusId = params.id!;
  const navigate = useNavigate();
  const qc = useQueryClient();

  const whoami = useQuery({ queryKey: ['whoami'], queryFn: api.whoami });
  const isAdmin = whoami.data?.persona === 'admin';
  const corpus = useQuery({
    queryKey: ['corpus', corpusId],
    queryFn: () => api.getCorpus(corpusId),
  });

  const plan = useQuery({
    queryKey: ['migration-plan', corpusId],
    queryFn: () => api.getCurrentMigrationPlan(corpusId),
    retry: false,
  });

  const generate = useMutation({
    mutationFn: () => api.generateMigrationPlan(corpusId, {}),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['migration-plan', corpusId] }),
  });
  const approve = useMutation({
    mutationFn: (planId: string) => api.approveMigrationPlan(planId),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['migration-plan', corpusId] }),
  });

  if (corpus.isPending) {
    return (
      <div className="mx-auto max-w-[1200px] space-y-3 p-6">
        <Skeleton className="h-8 w-72" />
        <Skeleton className="h-40" />
      </div>
    );
  }

  // 404 from the plan endpoint = no plan yet. Render an empty-state CTA.
  const noPlanYet = plan.isError && plan.error instanceof ApiError && plan.error.status === 404;

  return (
    <div className="mx-auto max-w-[1200px] space-y-6 p-6 lg:p-10" data-testid="migration-plan-page">
      <header className="space-y-1">
        <p className="font-mono text-caption uppercase tracking-wider text-ink-tertiary">
          Phase 8.0 · portfolio migration planning · {corpus.data?.name ?? corpusId}
        </p>
        <h1 className="text-display font-semibold text-ink-primary">Migration plan</h1>
        <p className="max-w-3xl text-body-lg text-ink-secondary">
          Dependency-aware wave assignment for the corpus's latest source version. Wave 1
          starts with leaf routines (no in-corpus callees); each subsequent wave depends only
          on routines in earlier waves.
        </p>
      </header>

      {plan.isPending && !noPlanYet && <Skeleton className="h-40" />}

      {noPlanYet && (
        <Card>
          <CardBody className="space-y-3 text-center">
            <Layers className="mx-auto h-8 w-8 text-ink-tertiary" />
            <p className="text-body text-ink-primary">No migration plan yet for this corpus.</p>
            <p className="text-body-sm text-ink-secondary">
              The planner reads the dependency graph and assigns every routine to a wave based
              on what it CALLs. Same graph in → same plan out, every time.
            </p>
            {isAdmin && (
              <Button
                variant="primary"
                onClick={() => generate.mutate()}
                disabled={generate.isPending}
                data-testid="generate-migration-plan"
              >
                <Play className={clsx('h-4 w-4', generate.isPending && 'animate-pulse')} />
                {generate.isPending ? 'Generating…' : 'Generate plan'}
              </Button>
            )}
            {!isAdmin && (
              <p className="font-mono text-caption text-ink-tertiary">
                Admin can generate the first plan. Switch persona from the top-right menu.
              </p>
            )}
          </CardBody>
        </Card>
      )}

      {plan.isError && !noPlanYet && (
        <ErrorBlock title="Could not load migration plan" message={String(plan.error)} />
      )}

      {plan.data && (
        <>
          <Card>
            <CardBody className="flex flex-wrap items-center justify-between gap-3">
              <div className="space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge tone={planTone(plan.data.plan.status)}>{plan.data.plan.status}</Badge>
                  <span className="font-mono text-caption text-ink-tertiary">
                    {plan.data.plan.strategyName}
                  </span>
                  <span className="font-mono text-caption text-ink-tertiary">
                    {plan.data.plan.totalWaves} waves · {plan.data.plan.totalRoutines} routines
                  </span>
                </div>
                <p className="text-body text-ink-primary">{plan.data.plan.summary}</p>
                <p className="font-mono text-caption text-ink-tertiary">
                  generated by {plan.data.plan.generatedBy ?? '—'} ·{' '}
                  {new Date(plan.data.plan.createdAt).toLocaleString()}
                  {plan.data.plan.approvedAt && (
                    <>
                      {' '}· approved by {plan.data.plan.approvedBy ?? '—'} ·{' '}
                      {new Date(plan.data.plan.approvedAt).toLocaleString()}
                    </>
                  )}
                </p>
              </div>
              {isAdmin && (
                <div className="flex flex-wrap items-center gap-2">
                  {plan.data.plan.status === 'draft' && (
                    <Button
                      variant="primary"
                      onClick={() => approve.mutate(plan.data!.plan.id)}
                      disabled={approve.isPending}
                      data-testid="approve-migration-plan"
                    >
                      <CheckCircle2 className="h-4 w-4" /> Approve plan
                    </Button>
                  )}
                  <Button
                    variant="secondary"
                    onClick={() => generate.mutate()}
                    disabled={generate.isPending}
                    data-testid="regenerate-migration-plan"
                  >
                    <Play className={clsx('h-4 w-4', generate.isPending && 'animate-pulse')} />
                    {generate.isPending ? 'Generating…' : 'Recompute plan'}
                  </Button>
                </div>
              )}
            </CardBody>
          </Card>

          {generate.isError && (
            <ErrorBlock
              title="Recompute failed"
              message={
                generate.error instanceof ApiError
                  ? generate.error.message
                  : String(generate.error)
              }
            />
          )}
          {approve.isError && (
            <ErrorBlock
              title="Approval failed"
              message={
                approve.error instanceof ApiError
                  ? approve.error.message
                  : String(approve.error)
              }
            />
          )}

          <div className="space-y-3">
            {plan.data.waves.map((w) => (
              <WaveCard
                key={w.id}
                wave={w}
                onOpenRoutine={(routineId) => navigate(`/subroutines/${routineId}`)}
              />
            ))}
          </div>
        </>
      )}

      <Card>
        <CardBody>
          <Link to={`/corpora/${corpusId}`} className="text-body-sm text-accent hover:underline">
            ← Back to corpus
          </Link>
          {' · '}
          <Link
            to={`/corpora/${corpusId}/dependency-graph`}
            className="text-body-sm text-accent hover:underline"
          >
            Open dependency graph
          </Link>
        </CardBody>
      </Card>
    </div>
  );
}

function planTone(status: string): 'success' | 'review' | 'superseded' | 'neutral' {
  if (status === 'approved') return 'success';
  if (status === 'draft') return 'review';
  if (status === 'archived') return 'superseded';
  return 'neutral';
}

function WaveCard({
  wave,
  onOpenRoutine,
}: {
  wave: MigrationPlanWave;
  onOpenRoutine: (routineId: string) => void;
}) {
  const lc = wave.liveCounts;
  return (
    <Card data-testid={`migration-wave-${wave.waveNumber}`}>
      <CardBody className="space-y-2">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div>
            <p className="font-mono text-caption uppercase tracking-wider text-ink-tertiary">
              wave {wave.waveNumber}
            </p>
            <h3 className="text-body-lg font-semibold text-ink-primary">{wave.name}</h3>
          </div>
          <div className="text-right font-mono text-caption text-ink-tertiary">
            <div>{wave.routineCount} routines</div>
            <div>
              signed: {lc.signed} · scaffolded: {lc.scaffolded} · committed: {lc.committed}
            </div>
          </div>
        </div>
        <ul className="grid grid-cols-1 gap-1 md:grid-cols-2 lg:grid-cols-3">
          {wave.routines.map((r) => (
            <RoutinePill key={r.id} routine={r} onClick={() => onOpenRoutine(r.id)} />
          ))}
        </ul>
      </CardBody>
    </Card>
  );
}

function RoutinePill({
  routine,
  onClick,
}: {
  routine: MigrationPlanWaveRoutine;
  onClick: () => void;
}) {
  const tone =
    routine.state === 'COMMITTED' ? 'success' :
    routine.state === 'SCAFFOLDED' ? 'scaffolded' :
    routine.state === 'SIGNED' ? 'success' :
    routine.state === 'DRAFT' || routine.state === 'IN_REVIEW' ? 'review' :
    'neutral';
  return (
    <li>
      <button
        onClick={onClick}
        className="group flex w-full items-center justify-between gap-2 rounded border border-border-subtle bg-raised px-2 py-1 text-left hover:bg-sunken"
      >
        <span className="truncate font-mono text-body-sm text-ink-primary">{routine.name}</span>
        <span className="flex items-center gap-1">
          <Badge tone={tone}>{routine.state}</Badge>
          <ArrowRight className="h-3 w-3 text-ink-tertiary opacity-0 group-hover:opacity-100" />
        </span>
      </button>
    </li>
  );
}
